server:
  port: 8082

spring:
  application:
    name: reminder-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/reminder_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.reminder.reminder: DEBUG