version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: reminder-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reminder_user_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - reminder-network

  # MongoDB数据库
  mongodb:
    image: mongo:4.4
    container_name: reminder-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - reminder-network

  # Redis缓存
  redis:
    image: redis:6.0-alpine
    container_name: reminder-redis
    ports:
      - "6379:6379"
    networks:
      - reminder-network

  # 服务发现
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - reminder-network

  # 用户服务
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - discovery-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/reminder_user_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka/
    networks:
      - reminder-network

  # 提醒服务
  reminder-service:
    build: ./reminder-service
    container_name: reminder-service
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
      - discovery-service
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/reminder_db
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka/
    networks:
      - reminder-network

  # 通知服务
  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8083:8083"
    depends_on:
      - redis
      - discovery-service
    environment:
      SPRING_REDIS_HOST: redis
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka/
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    networks:
      - reminder-network

  # 网关服务
  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
      - user-service
      - reminder-service
      - notification-service
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka/
    networks:
      - reminder-network

volumes:
  mysql_data:
  mongodb_data:

networks:
  reminder-network:
    driver: bridge